import type { JobProfile } from '../types/database';

export const INITIAL_JOB_PROFILES: JobProfile[] = [
  {
    id: 'operador-padrao',
    name: 'Operador de Atendimento',
    description: 'Atendimento geral receptivo ao cliente com rotinas de orientação, auxílio e registro de solicitações.',
    openness_weight: 55,
    conscientiousness_weight: 80,
    extraversion_weight: 60,
    agreeableness_weight: 85,
    emotional_stability_weight: 80,
    adaptability_weight: 75,
    resilience_weight: 80,
    social_maturity_weight: 90,
    operational_orientation_weight: 80,
    realistic_weight: 30,
    investigative_weight: 55,
    artistic_weight: 20,
    social_weight: 90,
    enterprising_weight: 45,
    conventional_weight: 80,
    active: true
  },
  {
    id: 'operador-critico',
    name: 'Operador de Atendimento Crítico',
    description: 'Atendimento voltado a casos de alto conflito, clientes insatisfeitos e recuperação de chamadas.',
    openness_weight: 55,
    conscientiousness_weight: 85,
    extraversion_weight: 55,
    agreeableness_weight: 85,
    emotional_stability_weight: 90,
    adaptability_weight: 85,
    resilience_weight: 95,
    social_maturity_weight: 90,
    operational_orientation_weight: 85,
    realistic_weight: 25,
    investigative_weight: 65,
    artistic_weight: 15,
    social_weight: 90,
    enterprising_weight: 45,
    conventional_weight: 85,
    active: true
  },
  {
    id: 'operador-vendas',
    name: 'Operador de Vendas',
    description: 'Atendimento ativo ou receptivo focado no atingimento de metas comerciais, persuasão e conversão.',
    openness_weight: 55,
    conscientiousness_weight: 75,
    extraversion_weight: 90,
    agreeableness_weight: 60,
    emotional_stability_weight: 85,
    adaptability_weight: 80,
    resilience_weight: 85,
    social_maturity_weight: 75,
    operational_orientation_weight: 90,
    realistic_weight: 20,
    investigative_weight: 35,
    artistic_weight: 30,
    social_weight: 65,
    enterprising_weight: 95,
    conventional_weight: 65,
    active: true
  },
  {
    id: 'operador-retencao',
    name: 'Operador de Retenção',
    description: 'Reversão de cancelamentos de serviços com argumentos de valor, ofertas e forte poder de negociação.',
    openness_weight: 60,
    conscientiousness_weight: 80,
    extraversion_weight: 85,
    agreeableness_weight: 70,
    emotional_stability_weight: 90,
    adaptability_weight: 85,
    resilience_weight: 90,
    social_maturity_weight: 85,
    operational_orientation_weight: 85,
    realistic_weight: 20,
    investigative_weight: 45,
    artistic_weight: 25,
    social_weight: 75,
    enterprising_weight: 90,
    conventional_weight: 70,
    active: true
  },
  {
    id: 'monitor-qualidade',
    name: 'Monitor de Qualidade',
    description: 'Auditoria minuciosa de chamadas, avaliação de conformidade com scripts e relatórios de apontamentos.',
    openness_weight: 70,
    conscientiousness_weight: 95,
    extraversion_weight: 40,
    agreeableness_weight: 60,
    emotional_stability_weight: 85,
    adaptability_weight: 70,
    resilience_weight: 85,
    social_maturity_weight: 65,
    operational_orientation_weight: 95,
    realistic_weight: 20,
    investigative_weight: 85,
    artistic_weight: 20,
    social_weight: 45,
    enterprising_weight: 35,
    conventional_weight: 95,
    active: true
  },
  {
    id: 'suporte-especializado',
    name: 'Suporte / Atendimento Especializado',
    description: 'Resolução de chamados técnicos de 2º nível com diagnóstico profundo de erros e suporte avançado.',
    openness_weight: 75,
    conscientiousness_weight: 90,
    extraversion_weight: 50,
    agreeableness_weight: 75,
    emotional_stability_weight: 85,
    adaptability_weight: 80,
    resilience_weight: 85,
    social_maturity_weight: 80,
    operational_orientation_weight: 90,
    realistic_weight: 35,
    investigative_weight: 90,
    artistic_weight: 25,
    social_weight: 70,
    enterprising_weight: 40,
    conventional_weight: 90,
    active: true
  },
  {
    id: 'lider-equipe',
    name: 'Líder de Equipe',
    description: 'Acompanhamento direto de operadores no hall, auxílio em chamadas difíceis e suporte operacional diário.',
    openness_weight: 70,
    conscientiousness_weight: 85,
    extraversion_weight: 80,
    agreeableness_weight: 80,
    emotional_stability_weight: 85,
    adaptability_weight: 80,
    resilience_weight: 85,
    social_maturity_weight: 90,
    operational_orientation_weight: 85,
    realistic_weight: 25,
    investigative_weight: 60,
    artistic_weight: 25,
    social_weight: 85,
    enterprising_weight: 85,
    conventional_weight: 75,
    active: true
  },
  {
    id: 'supervisor-operacao',
    name: 'Supervisor de Operação',
    description: 'Gestão executiva de equipe de contact center com controle de indicadores, absenteísmo e resultados.',
    openness_weight: 70,
    conscientiousness_weight: 85,
    extraversion_weight: 85,
    agreeableness_weight: 75,
    emotional_stability_weight: 90,
    adaptability_weight: 85,
    resilience_weight: 90,
    social_maturity_weight: 90,
    operational_orientation_weight: 90,
    realistic_weight: 25,
    investigative_weight: 55,
    artistic_weight: 25,
    social_weight: 80,
    enterprising_weight: 90,
    conventional_weight: 75,
    active: true
  },
  {
    id: 'analista-atendimento',
    name: 'Analista de Atendimento',
    description: 'Análise estratégica de dados de chamadas, volume de filas, dashboards e melhorias de procedimentos.',
    openness_weight: 80,
    conscientiousness_weight: 90,
    extraversion_weight: 50,
    agreeableness_weight: 65,
    emotional_stability_weight: 85,
    adaptability_weight: 80,
    resilience_weight: 80,
    social_maturity_weight: 70,
    operational_orientation_weight: 90,
    realistic_weight: 20,
    investigative_weight: 90,
    artistic_weight: 30,
    social_weight: 55,
    enterprising_weight: 50,
    conventional_weight: 90,
    active: true
  },
  {
    id: 'ouvidoria',
    name: 'Ouvidoria',
    description: 'Tratamento de demandas de clientes em última instância com imparcialidade, síntese e alta diplomacia.',
    openness_weight: 65,
    conscientiousness_weight: 90,
    extraversion_weight: 60,
    agreeableness_weight: 90,
    emotional_stability_weight: 95,
    adaptability_weight: 90,
    resilience_weight: 95,
    social_maturity_weight: 95,
    operational_orientation_weight: 85,
    realistic_weight: 20,
    investigative_weight: 75,
    artistic_weight: 20,
    social_weight: 95,
    enterprising_weight: 55,
    conventional_weight: 85,
    active: true
  }
];
